# Homebrew setup (custom location)
export PATH="$HOME/homebrew/bin:$PATH"
export HOMEBREW_PREFIX="$HOME/homebrew"
export HOMEBREW_REPOSITORY="$HOME/homebrew"
export HOMEBREW_CELLAR="$HOME/homebrew/Cellar"

export EDITOR='nvim'
export VISUAL='nvim'

export LANG="en_IN.UTF-8"
source $HOME/.local/share/fonts/i_dev.sh

#bind -s '"\C-f":"~/.dotfiles/tmux/tmux-sessionizer\n"'
# bind -s '"\C-f":"\C-ubash -c '\''~/.dotfiles/tmux/tmux-sessionizer'\''\n"'
# bind -s '"\C-o":"\C-ubash -c '\''tmux a'\''\n"'
#bind -s '"\C-o":"tmux a"'

# for golang
export PATH=$PATH:/usr/local/go/bin

## for rust
# cmd : source "$HOME/.cargo/env" will write the line below to the bashrc
. "$HOME/.cargo/env"

# custom aliases
alias nv='nvim .'
alias ..='cd ..'
alias ....='cd ../../'

if [ -f ~/.fzf.bash ]; then
  source ~/.fzf.bash
fi

# for persisting ssh-agent across different sessions
SSH_ENV="$HOME/.ssh/environment"

function start_agent {
    (
        umask 066
        ssh-agent >"$SSH_ENV"
    )
    . "$SSH_ENV" >/dev/null
}

function add_ssh_keys {
    ssh-add -l &>/dev/null
    if [ "$?" != "0" ]; then
        ssh-add ~/.ssh/bit_bucket_id_ed25519 &> /dev/null
        ssh-add ~/.ssh/github-ed25519 &> /dev/null
    fi
}

# Load ssh-agent settings
if [ -f "$SSH_ENV" ]; then
    . "$SSH_ENV" >/dev/null
    # Verify if the agent is running, if not, start it
    if ! pgrep -u "$USER" ssh-agent >/dev/null; then
        start_agent
    fi
else
    start_agent
fi

# Only add keys if they're not already loaded
add_ssh_keys


export PATH="$PATH:~/.local/bin"

# Lazy load NVM (saves ~0.223s on startup)
export NVM_DIR="$HOME/.nvm"
nvm() {
    unset -f nvm
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    nvm "$@"
}

# Lazy load node, npm, npx
for cmd in node npm npx; do
    eval "${cmd}() {
        unset -f node npm npx nvm
        [ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"
        [ -s \"$NVM_DIR/bash_completion\" ] && . \"$NVM_DIR/bash_completion\"
        ${cmd} \"\$@\"
    }"
done

export PATH="/Users/harudaylnu/homebrew/opt/openjdk/bin:$PATH"
# export JAVA_HOME="/Users/harudaylnu/Library/Java/JavaVirtualMachines/corretto-17.0.15/Contents/Home/"
export JAVA_HOME="/Users/harudaylnu/Library/Java/JavaVirtualMachines/corretto-11.0.28/Contents/Home/"
#export JAVA_HOME="/Users/harudaylnu/Library/Java/JavaVirtualMachines/corretto-21.0.7/Contents/Home"
#export JAVA_HOME="/Users/harudaylnu/homebrew/opt/openjdk"

alias lua=luajit


eval "$(starship init bash)"

# Lazy load Angular CLI autocompletion (saves ~0.289s on startup)
ng() {
    unset -f ng
    source <(command ng completion script)
    ng "$@"
}

# Lazy load docker completion (saves ~0.021s on startup)
docker() {
    unset -f docker
    source <(command docker completion bash)
    docker "$@"
}


# nvim related
export JDTLS_JVM_ARGS='-javaagent:/Users/harudaylnu/.local/share/nvim/mason/share/jdtls/lombok.jar'

alias cls=clear


